# This is a basic workflow to help you get started with Actions

name: Build and Push to GCP

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    types:
      - closed
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-push-gar:
    name: Build and Push to Artifact Registry
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: dalle_nano
      PROJECTID: total-thinker-356217
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true
        
    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME .
      
    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker us-west2-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: 1
      run: |-
        docker tag $IMAGE_NAME us-west2-docker.pkg.dev$PROJECT_ID/practice/$IMAGE_NAME
        docker push us-west2-docker.pkg.dev$PROJECT_ID/practice/$IMAGE_NAME
