---
name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: check
      run: $${{secrets.SERVICE_ACCOUNT_KEY}}
